version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./app:/app

    php:
        build: .
        volumes:
            - ./app:/app

    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: ''
            MYSQL_DATABASE: 'etudiants'
        volumes:
            - mysqldata:/var/lib/mysql
            - "./devtools/db:/docker-entrypoint-initdb.d"
        ports:
            - 3306:3306
volumes:
    mysqldata: {}
